name: flutter_scroll_to_top
description: A package that provides a simple wrapper to wrap your scrollable widgets in, that lets
  you show a scroll to top prompt to the user when they scroll.
version: 2.2.4-beta
homepage: https://github.com/NamanShergill/flutter_scroll_to_top

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter